language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - ./configure --prefix=$HOME/cargo-install --disable-cross-tests --disable-optimize
  - make
  - make test
  - make distcheck
  - make doc
  - make install
  - make uninstall
after_success:
  - travis-cargo --only nightly doc-upload
  - travis-cargo coveralls --no-sudo --verify

env:
  global:
    secure: NPKMWqUiZ+FzOmvgLDrUiQkOQhKSrmUiB6qUTWK0uLnyJa31EZw7eW5WRcN/bkCE5cVj5ZSW9EFuejFb/VL8N/to4MvYh5uFIgKMXrW5ZIuAvM2GtJuOr58VS2KtvS1hNIIIQUzfBkRFXz/jS3aWjv2hDLk2lTQCTCKt1FT7xZQ=

os:
  - linux
  - osx

branches:
  only:
    - master

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
