trigger:
  branches:
    include:
    - '*'
    exclude:
    - master
pr:
- master

jobs:
- job: Windows
  pool:
    vmImage: windows-2019
  steps:
    - template: ci/azure-install-rust.yml
  strategy:
    matrix:
      x86_64-msvc:
        TOOLCHAIN: stable-x86_64-pc-windows-msvc
        OTHER_TARGET: i686-pc-windows-msvc
