[package]
name = "cargo"
version = "0.43.0"
edition = "2018"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
homepage = "https://crates.io"
repository = "https://github.com/rust-lang/cargo"
documentation = "https://docs.rs/cargo"
readme = "README.md"
description = """
Cargo, a package manager for Rust.
"""

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
atty = "0.2"
bytesize = "1.0"
cargo-platform = { path = "crates/cargo-platform", version = "0.1.1" }
crates-io = { path = "crates/crates-io", version = "0.31" }
crossbeam-utils = "0.7"
crypto-hash = "0.3.4"
curl = { version = "0.4.25", features = ["http2"] }
curl-sys = "0.4.25"
env_logger = "0.7.1"
pretty_env_logger = { version = "0.3", optional = true }
anyhow = "1.0"
filetime = "0.2"
flate2 = { version = "1.0.13", features = ["zlib"] }
fs2 = "0.4"
git2 = "0.11.0"
git2-curl = "0.12.0"
glob = "0.3.0"
hex = "0.4"
home = "0.5"
humantime = "1.3.0"
ignore = "0.4.11"
lazy_static = "1.4.0"
jobserver = "0.1.19"
lazycell = "1.2.1"
libc = "0.2"
log = "0.4.8"
libgit2-sys = "0.10.0"
memchr = "2.3.0"
num_cpus = "1.12.0"
opener = "0.4"
percent-encoding = "2.1.0"
remove_dir_all = "0.5.2"
rustfix = "0.5.0"
same-file = "1"
semver = { version = "0.9.0", features = ["serde"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_ignored = "0.1.1"
serde_json = { version = "1.0.44", features = ["raw_value"] }
shell-escape = "0.1.4"
strip-ansi-escapes = "0.1.0"
tar = { version = "0.4.26", default-features = false }
tempfile = "3.1.0"
termcolor = "1.1.0"
toml = "0.5.6"
url = "2.1.1"
walkdir = "2.3.1"
clap = "2.33.0"
unicode-width = "0.1.7"
openssl = { version = '0.10.26', optional = true }
im-rc = "14.1.0"

# A noop dependency that changes in the Rust repository, it's a bit of a hack.
# See the `src/tools/rustc-workspace-hack/README.md` file in `rust-lang/rust`
# for more information.
rustc-workspace-hack = "1.0.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = { version = "0.7.0", features = ["mac_os_10_7_support"] }

[target.'cfg(windows)'.dependencies]
miow = "0.3.3"
fwdansi = "1"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = [
  "basetsd",
  "handleapi",
  "jobapi",
  "jobapi2",
  "memoryapi",
  "minwindef",
  "ntdef",
  "ntstatus",
  "processenv",
  "processthreadsapi",
  "psapi",
  "synchapi",
  "winerror",
  "winbase",
  "wincon",
  "winnt",
]

[dev-dependencies]
cargo-test-macro = { path = "crates/cargo-test-macro", version = "0.1.0" }
cargo-test-support = { path = "crates/cargo-test-support", version = "0.1.0" }

[[bin]]
name = "cargo"
test = false
doc = false

[features]
deny-warnings = []
vendored-openssl = ["openssl/vendored"]
pretty-env-logger = ["pretty_env_logger"]
