[project]
name = "cargo"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>",
           "Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]

[profile.test]
debug = false
[profile.dev]
debug = false

[lib]
name = "cargo"
path = "src/cargo/lib.rs"

[dependencies]
toml = "0.1.8"
semver = "0.1.9"
curl = "0.1.5"
tar = "0.1.4"
flate2 = "0.1.3"
git2 = "0.1.6"
glob = "0.1.4"
time = "0.1.9"
log = "0.1.7"
docopt = "0.6.22"
url = "0.2.13"
rustc-serialize = "0.2.3"
term = "0.1"

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"

[dependencies.registry]
path = "src/registry"

[[bin]]
name = "cargo"
test = false
doc = false

[[test]]
name = "tests"
[[bench]]
name = "tests"
path = "tests/tests.rs"

[[test]]
name = "resolve"
